image: "rust:latest"

stages:
  - build
  - test

build:
  stage: build
  script:
    - make whack
  artifacts:
    paths:
      - target

unitTest:
  stage: test
  script:
    - make test

integrationTest:
  stage: test
  script:
    - git submodule update --init
    - python3 integration_test.py
