image: "rust:latest"

variables:
  IMAGE_TAG: whack-36

stages:
  - build
  - test

build-docker-image:
  stage: build
  before_script:
    # install docker
    - curl -fsSL https://get.docker.com -o get-docker.sh
    - sh ./get-docker.sh
    - apt install sudo
    
  script:
    - docker -v /var/run/docker.sock:/var/run/docker.sock stop $IMAGE_TAG || true
    - docker -v /var/run/docker.sock:/var/run/docker.sock rm $IMAGE_TAG || true
    - docker -v /var/run/docker.sock:/var/run/docker.sock rmi $IMAGE_TAG || true
    - docker -v /var/run/docker.sock:/var/run/docker.sock build -t $IMAGE_TAG .
    - docker -v /var/run/docker.sock:/var/run/docker.sock run -it -d --name $IMAGE_TAG $IMAGE_TAG /bin/bash

unitTest:
  stage: test
  script:
    - docker -v /var/run/docker.sock:/var/run/docker.sock exec -i $IMAGE_TAG /bin/sh -c "make test"

integrationTest:
  stage: test
  script:
    - docker -v /var/run/docker.sock:/var/run/docker.sock exec -i $IMAGE_TAG /bin/sh -c "python3 integration_test.py"
