image: "rust:latest"

stages:
  - build
  - test

build:
  stage: build
  script:
    - make whack
  artifacts:
    paths:
      - target

unitTest:
  stage: test
  script:
    - make test

integrationTest:
  stage: test
  before_script:
    - git submodule update --init --recursive
    - apt-get update
    - apt-get install -y ruby
    - gem install rest-client
  script:
    - python3 integration_test.py wacc-examples-36
