image: "rust:latest"

variables:
  IMAGE_TAG: whack-36

stages:
  - build
  - test

build-docker-image:
  stage: build
  before_script:
    # install docker
    - apt update
    - apt install apt-utils
    - apt install sudo
    - curl -fsSL https://get.docker.com -o get-docker.sh
    - sh ./get-docker.sh
    
  script:
    - sudo docker stop $IMAGE_TAG || true
    - sudo docker rm $IMAGE_TAG || true
    - sudo docker rmi $IMAGE_TAG || true
    - sudo docker build -t $IMAGE_TAG .
    - sudo docker run -it -d --name $IMAGE_TAG $IMAGE_TAG /bin/bash

unitTest:
  stage: test
  script:
    - sudo docker exec -i $IMAGE_TAG /bin/sh -c "make test"

integrationTest:
  stage: test
  script:
    - sudo docker exec -i $IMAGE_TAG /bin/sh -c "python3 integration_test.py"
