image: "rust:latest"

stages:
  - build
  - test

build:
  stage: build
  script:
    - make whack
  artifacts:
    paths:
      - target

unitTest:
  stage: test
  script:
    - make test

integrationTest:
  stage: test
  script:
    - git clone https://gitlab+deploy-token-74:gldt-rnEPvS7oCQYNgBGpeS5F@gitlab.doc.ic.ac.uk/yz9522/wacc-examples-36.git
    - python3 integration_test.py
