image: "rust:latest"

stages:
  - build
  - test

build:
  stage: build
  script:
    - make whack
  artifacts:
    paths:
      - target

unitTest:
  stage: test
  script:
    - make test

integrationTest:
  stage: test
  before_script:
    - rm -rf wacc-examples-36 || true
    - git clone https://$username:$token@gitlab.doc.ic.ac.uk/yz9522/wacc-examples-36.git
  script:
    - python3 integration_test.py
