image: "rust:latest"

variables:
  IMAGE_TAG: whack-36

stages:
  - build
  - test

build:
  stage: build
  script:
    - make build
  artifects:
    paths:
      - target

unitTest:
  stage: test
  script:
    - make test

integrationTest:
  stage: test
  before-script:
    - git submodule update --init --recursive
    - apt-get update
    - apt-get install -y ruby
    - gem install rest-client
  script:
    - python3 intregraionTest.py
