image: "rust:latest"

variables:
  IMAGE_TAG: whack

stages:
  - build
  - test

build-docker-image:
  stage: build
  script:
    - docker stop $IMAGE_TAG || true
    - docker rm $IMAGE_TAG || true
    - docker rmi $IMAGE_TAG || true
    - docker build -t $IMAGE_TAG .
    - docker run -it -d --name $IMAGE_TAG $IMAGE_TAG /bin/bash

unitTest:
  stage: test
  script:
    - docker exec -i $IMAGE_TAG /bin/sh -c "make test"

integrationTest:
  stage: test
  script:
    - docker exec -i $IMAGE_TAG /bin/sh -c "python3 integration_test.py"
