image: "rust:latest"

stages:
  - build
  - test

build:
  stage: build
  script:
    - make whack
  artifacts:
    paths:
      - target

unitTest:
  stage: test
  script:
    - make test

integrationTest:
  stage: test
  before_script:
    - git submodule update --init --recursive
    - apt-get update || true
    - apt-get install -y ruby || true
    - gem install rest-client || true
  script:
    - python3 integration_test.py wacc-examples-36/valid/IO wacc-examples-36/valid/basic \
      wacc-examples-36/valid/if wacc-examples-36/valid/while \
      wacc-examples-36/valid/expressions wacc-examples-36/valid/scope \
      wacc-examples-36/valid/sequence wacc-examples-36/valid/variables \
      wacc-examples-36/valid/function wacc-examples-36/valid/pairs \
      wacc-examples-36/valid/array wacc-examples-36/valid/runtimeErr \
      wacc-examples-36/invalid/syntaxErr wacc-examples-36/invalid/semanticErr
